version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  zero2prod:
    build: .
    ports:
      - "1202:1202"
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge
