database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
application:
  port: 1202
email_client:
  base_url: "localhost:"
  sender_email: "test@gamil.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
  
  
