name: Deploy to Aliyun via Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        # 把所有要在远程脚本里用到的变量都放这里
        env:
          APP_HOST:       "0.0.0.0"
          APP_PORT:       "1202"
          DB_HOST:        "db"
          DB_PORT:        "5432"
          DB_USERNAME:    ${{ secrets.DB_USERNAME }}
          DB_PASSWORD:    ${{ secrets.DB_PASSWORD }}
          DB_NAME:        "newsletter"
          DB_REQUIRE_SSL: false
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          script: |
            cd ~/apps/zero2prod_my
            git pull origin main

            cat > configuration/production.yaml <<EOF
            application:
              host: ${APP_HOST}
              port: ${APP_PORT}

            database:
              host: "${DB_HOST}"
              port: ${DB_PORT}
              username: "${DB_USERNAME}"
              password: "${DB_PASSWORD}"
              database_name: "${DB_NAME}"
              require_ssl: ${DB_REQUIRE_SSL}
            EOF

            docker-compose down
            docker-compose build
            docker-compose up -d
